# Generated by Django 4.1.5 on 2023-02-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quality')),
                ('convert', models.CharField(choices=[('NO_FILTER', 'No Filter'), ('PNG', 'PNG'), ('JPG', 'JPG'), ('JPED', 'JPED'), ('WEBP', 'WEBP'), ('SVG', 'SVG')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='filter')),
                ('filter', models.CharField(choices=[('NO_FILTER', 'No filter'), ('COLORIZED', 'Colorized'), ('GRAYSCALE', 'Grayscale'), ('BLURRED', 'Blurred'), ('BINARY', 'Binary'), ('INVERT', 'Invert')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('action', models.CharField(choices=[('NO_FILTER', 'no filter'), ('COLORIZED', 'colorized'), ('GRAYSCALE', 'grayscale'), ('BLURRED', 'blurred'), ('BINARY', 'binary'), ('INVERT', 'invert')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
