# Generated by Django 4.1.5 on 2023-02-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
