# Generated by Django 4.1.5 on 2023-01-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenapp', '0002_imagequality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagequality',
            name='quality',
            field=models.CharField(choices=[('NO_FILTER', 'no filter'), ('PNG', 'PNG'), ('JPG', 'JPG'), ('JPED', 'JPED'), ('WEBP', 'WEBP'), ('SVG', 'SVG')], max_length=100),
        ),
    ]
