# Generated by Django 4.1.5 on 2023-01-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenapp', '0003_alter_imagequality_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quality')),
                ('convert', models.CharField(choices=[('NO_FILTER', 'No Filter'), ('PNG', 'PNG'), ('JPG', 'JPG'), ('JPED', 'JPED'), ('WEBP', 'WEBP'), ('SVG', 'SVG')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageQuality',
        ),
    ]
