# Generated by Django 4.1.5 on 2023-01-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenapp', '0004_imageconvert_delete_imagequality'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='filter')),
                ('filter', models.CharField(choices=[('NO_FILTER', 'No filter'), ('COLORIZED', 'Colorized'), ('GRAYSCALE', 'Grayscale'), ('BLURRED', 'Blurred'), ('BINARY', 'Binary'), ('INVERT', 'Invert')], max_length=100)),
            ],
        ),
    ]
